In [4]:
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer

In [2]:
vectorizer = CountVectorizer()

In [29]:
docs = np.array(['Mirabai has won a silver medal in weight lifting in Tokyo olympics 2021',
                 'Sindhu has won a bronze medal in badminton in Tokyo olympics',
                 'Indian hockey team is in top four team in Tokyo olympics 2021 after 40 years'])

In [30]:
# Fit the bag-of-words model

bag = vectorizer.fit_transform(docs)

In [31]:
#
# Get unique words / tokens found in all the documents. The unique words / tokens represents
# the features
#
print(vectorizer.get_feature_names_out())

['2021' '40' 'after' 'badminton' 'bronze' 'four' 'has' 'hockey' 'in'
 'indian' 'is' 'lifting' 'medal' 'mirabai' 'olympics' 'silver' 'sindhu'
 'team' 'tokyo' 'top' 'weight' 'won' 'years']


In [32]:
#
# Associate the indices with each unique word
#
print(vectorizer.vocabulary_)

{'mirabai': 13, 'has': 6, 'won': 21, 'silver': 15, 'medal': 12, 'in': 8, 'weight': 20, 'lifting': 11, 'tokyo': 18, 'olympics': 14, '2021': 0, 'sindhu': 16, 'bronze': 4, 'badminton': 3, 'indian': 9, 'hockey': 7, 'team': 17, 'is': 10, 'top': 19, 'four': 5, 'after': 2, '40': 1, 'years': 22}


In [33]:
#
# Print the numerical feature vector
#
print(bag.toarray())

[[1 0 0 0 0 0 1 0 2 0 0 1 1 1 1 1 0 0 1 0 1 1 0]
 [0 0 0 1 1 0 1 0 2 0 0 0 1 0 1 0 1 0 1 0 0 1 0]
 [1 1 1 0 0 1 0 1 2 1 1 0 0 0 1 0 0 2 1 1 0 0 1]]


In [56]:
#
# Creating training data set from bag-of-words  and dummy label
#
X = bag.toarray()
y = np.array([1, 1, 0])

In [35]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [57]:
#
# Create training and test split
#
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [47]:
print(y_test)

[0]


In [54]:
#
# Create an instance of LogisticRegression classifier
#
lr = LogisticRegression(C=100.0, random_state=1, solver='lbfgs', multi_class='ovr')

In [58]:
#
# Fit the model
#
lr.fit(X_train, y_train)

LogisticRegression(C=100.0, multi_class='ovr', random_state=1)

In [42]:
#
# Create the predictions
#
y_predict = lr.predict(X_test)

In [43]:
# Use metrics.accuracy_score to measure the score
print("LogisticRegression Accuracy %.3f" %metrics.accuracy_score(y_test, y_predict))

LogisticRegression Accuracy 1.000
